import type { Wallet } from "@/core/entities/wallet"

export const MOCK_WALLET: Wallet = {
  id: "wallet-1",
  studentId: "mock-user-1",
  balance: 5.5,
  totalHours: 8,
  plan: "mensal",
  planValue: 449,
  expiresAt: "2026-04-30",
  transactions: [
    {
      id: "tx-1",
      walletId: "wallet-1",
      lessonId: "lesson-past-1",
      type: "debit",
      hours: -0.9,
      balanceAfter: 5.5,
      professorName: "Paulinho",
      classLevel: "Nível B",
      isOffPeak: false,
      createdAt: "2026-03-28T19:00:00.000Z",
    },
    {
      id: "tx-2",
      walletId: "wallet-1",
      lessonId: "lesson-past-2",
      type: "debit",
      hours: -0.86,
      balanceAfter: 6.4,
      professorName: "Paulinho",
      classLevel: "Nível B",
      isOffPeak: true,
      createdAt: "2026-03-26T09:00:00.000Z",
    },
    {
      id: "tx-3",
      walletId: "wallet-1",
      lessonId: "lesson-past-3",
      type: "debit",
      hours: -1.5,
      balanceAfter: 7.26,
      professorName: "Marília",
      classLevel: "Nível A",
      isOffPeak: false,
      createdAt: "2026-03-21T19:30:00.000Z",
    },
    {
      id: "tx-4",
      walletId: "wallet-1",
      lessonId: null,
      type: "credit",
      hours: 8,
      balanceAfter: 8.76,
      professorName: null,
      classLevel: null,
      isOffPeak: null,
      createdAt: "2026-03-01T10:00:00.000Z",
    },
  ],
}
