import type { Wallet } from "@/core/entities/wallet"

export const MOCK_WALLET: Wallet = {
  id: "wallet-1",
  studentId: "mock-user-1",
  balance: 5.5,
  totalPlays: 8,
  plan: "mensal",
  playValue: 5.125,
  expiresAt: "2026-04-30",
  transactions: [
    {
      id: "tx-1",
      walletId: "wallet-1",
      studentId: "mock-user-1",
      lessonId: "lesson-past-1",
      type: "debit",
      amount: -10,
      balanceAfter: 5,
      professorName: "Paulinho",
      classLevel: "Nível B",
      isPeak: true,
      isReserva: false,
      createdAt: "2026-03-28T19:00:00.000Z",
    },
    {
      id: "tx-2",
      walletId: "wallet-1",
      studentId: "mock-user-1",
      lessonId: "lesson-past-2",
      type: "debit",
      amount: -10,
      balanceAfter: 15,
      professorName: "Paulinho",
      classLevel: "Nível B",
      isPeak: false,
      isReserva: false,
      createdAt: "2026-03-26T09:00:00.000Z",
    },
    {
      id: "tx-3",
      walletId: "wallet-1",
      studentId: "mock-user-1",
      lessonId: "lesson-past-3",
      type: "debit",
      amount: -18,
      balanceAfter: 25,
      professorName: "Marília",
      classLevel: "Nível A",
      isPeak: true,
      isReserva: false,
      createdAt: "2026-03-21T19:30:00.000Z",
    },
    {
      id: "tx-4",
      walletId: "wallet-1",
      studentId: "mock-user-1",
      lessonId: null,
      type: "purchase",
      amount: 80,
      balanceAfter: 80,
      professorName: null,
      classLevel: null,
      isPeak: null,
      createdAt: "2026-03-01T10:00:00.000Z",
    },
  ],
}
