// src/core/math/financial-engine.ts

export interface CheckinRevenue {
  /** Gross revenue in BRL generated by the check-in (playsConsumed × playValue). */
  readonly rsBruto: number
  /** Amount credited to the professor in BRL. */
  readonly professorCredit: number
  /** Amount credited to the arena in BRL. */
  readonly arenaCredit: number
}

export interface ProfessorShareConfig {
  /** Percentage of revenue credited to the professor (0–1). */
  readonly professorSharePct: number
  /** Percentage of revenue credited to the arena (0–1). */
  readonly arenaSharePct: number
}

/**
 * Calculates the gross revenue and its split between professor and arena
 * for a single check-in event.
 *
 * Receives the share percentages directly — no PROFESSOR_MAP lookup.
 * Values must be snapshotted into the lesson document at creation time
 * so they are independent of runtime configuration.
 *
 * @param playsConsumed - Integer Plays deducted from the student's wallet.
 * @param playValue     - Monetary value of one Play for the student's plan (R$).
 * @param shareConfig   - Professor and arena revenue split percentages.
 */
export function calculateCheckinRevenue(
  playsConsumed: number,
  playValue: number,
  shareConfig: ProfessorShareConfig,
): CheckinRevenue {
  const rsBruto = playsConsumed * playValue

  return {
    rsBruto,
    professorCredit: rsBruto * shareConfig.professorSharePct,
    arenaCredit: rsBruto * shareConfig.arenaSharePct,
  }
}
