// src/core/math/financial-engine.ts

import { getProfessorById } from "@/core/constants/professors"
import { ProfessorNotFoundError } from "@/core/errors/exceptions"
import { ERROS } from "@/core/errors/erros"

export interface CheckinRevenue {
  /** Gross revenue in BRL generated by the check-in (playsConsumed × playValue). */
  readonly rsBruto: number
  /** Amount credited to the professor in BRL. */
  readonly professorCredit: number
  /** Amount credited to the arena in BRL. */
  readonly arenaCredit: number
}

/**
 * Calculates the gross revenue and its split between professor and arena
 * for a single check-in event.
 *
 * @param playsConsumed - Integer Plays deducted from the student's wallet.
 * @param playValue     - Monetary value of one Play for the student's plan (R$).
 * @param professorId   - Professor identifier used to look up the revenue split.
 */
export function calculateCheckinRevenue(
  playsConsumed: number,
  playValue: number,
  professorId: string,
): CheckinRevenue {
  const config = getProfessorById(professorId)
  if (!config) {
    throw new ProfessorNotFoundError(ERROS.PROFESSOR_NAO_ENCONTRADO(professorId))
  }

  const rsBruto = playsConsumed * playValue

  return {
    rsBruto,
    professorCredit: rsBruto * config.professorSharePct,
    arenaCredit: rsBruto * config.arenaSharePct,
  }
}
